import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });
import LineChart from "../components/lineChart"
import NavbarWrapper from "@/components/navbarWrapper";

export const metadata = {
  title: "CRM Skill Capital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="https://www.skillcapital.ai/images/favicon.png"></link>
      <body className={inter.className}><NavbarWrapper />{children}</body>
    </html>
  );
}
